# Generated by Django 5.2.4 on 2025-07-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.artwork'),
        ),
    ]
